FROM golang:1.9.4 AS build

RUN apt-get update
RUN apt-get install -y git libreadline-dev

RUN go-wrapper download github.com/nathany/looper
RUN go-wrapper install github.com/nathany/looper

RUN mkdir -p /go/src/github.com/ripta/tpl
VOLUME /go/src/github.com/ripta/tpl
WORKDIR /go/src/github.com/ripta/tpl
